export default function Float() {
  return (
    <div id="wd-float-divs">
      <h2>Float</h2>
      <div>
        <img className="wd-float-right"
        src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam elit nulla, dictum a vulputate ut, egestas nec augue. Fusce vitae nulla tincidunt, porttitor sapien quis, rutrum erat. Aliquam erat volutpat. Vestibulum volutpat auctor lorem, a varius lacus ultrices id. Sed convallis, ante ullamcorper auctor euismod, nulla sem maximus metus, nec consectetur ante massa at felis. Ut enim lacus, eleifend at malesuada id, vehicula id nulla. Praesent non nibh et lectus dapibus fringilla. Duis finibus metus augue, in aliquet magna euismod tincidunt. Proin at quam nec lectus placerat blandit sit amet et justo. 
        Cras eleifend ut justo ullamcorper porttitor. Phasellus luctus velit nunc, eu imperdiet felis dictum ac. Pellentesque vitae metus faucibus, cursus neque eu, vestibulum velit. Vivamus tristique nisi eleifend tellus fringilla dictum. Nulla ut erat a augue gravida consequat vitae tincidunt dui. Curabitur sed nunc hendrerit, rhoncus ipsum pharetra, scelerisque risus. Cras commodo iaculis congue. Nam dignissim neque id lectus bibendum rhoncus. Mauris at tincidunt lectus. Aenean odio mi, placerat ut pulvinar quis, facilisis volutpat libero. Sed aliquam elit quis dui pharetra pellentesque. Donec vel eros pharetra, sollicitudin libero quis, hendrerit lorem. Nunc a gravida nisl. 
        Etiam ullamcorper lectus at odio ullamcorper, eget varius libero interdum. Suspendisse tempor, ex ac eleifend vestibulum, elit massa imperdiet tellus, ut dapibus leo nulla vitae mauris. Pellentesque tempus accumsan luctus. Curabitur semper, justo vitae auctor tempor, massa ligula ultrices leo, et laoreet dui turpis et turpis. Sed dignissim orci ut felis finibus tempus. Proin turpis risus, porta non odio at, iaculis lobortis sapien. Etiam eleifend semper tortor accumsan ultricies. 
        <img className="wd-float-left"
        src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
        Nulla scelerisque malesuada dui. Maecenas eget lobortis est. Vivamus sit amet ultrices velit. Duis suscipit nec mauris id imperdiet. Mauris maximus volutpat massa nec commodo. Donec convallis mauris eget tristique condimentum. Quisque eleifend facilisis mauris, non laoreet turpis viverra vitae. Nulla sodales porttitor pellentesque. Morbi in sapien sodales, dapibus urna sit amet, dapibus eros. Proin venenatis justo augue, ut consectetur urna pulvinar quis. 
        Sed et convallis diam, eget vehicula dui. Mauris libero tortor, tempus non dapibus vitae, sollicitudin non purus. Praesent tristique, elit in consequat lobortis, augue est pulvinar magna, sit amet tempor mi ipsum ac ante. Etiam nunc sem, porta id facilisis eget, mollis ut tortor. Integer a ultricies nunc. Quisque vel lacus vulputate, venenatis nisl quis, egestas enim. Sed in lorem vitae eros pulvinar tempor eget vel enim. Morbi a orci vulputate, suscipit erat sit amet, facilisis risus. Ut molestie, nulla sit amet imperdiet ornare, quam leo dapibus arcu, vel fringilla quam quam vel sapien. Integer a metus nisl. Nullam posuere diam vel augue consequat bibendum. Sed interdum dapibus enim, sed lobortis felis luctus a. Nam dui tellus, blandit et enim non, dapibus sodales dolor. 
        Vivamus sollicitudin sollicitudin odio, non ullamcorper elit ultrices a. Phasellus et varius arcu. Etiam at ipsum consectetur, tempor leo non, fermentum risus. Sed vitae enim luctus, ullamcorper nisi non, cursus quam. Aliquam dignissim vitae erat sed pretium. Suspendisse rhoncus est sed aliquet tempor. Aenean sollicitudin, risus vel convallis dapibus, urna tortor ultricies mauris, ac dapibus nisi leo a felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce efficitur eu tellus et malesuada. Vestibulum turpis libero, consectetur sed tempor eget, feugiat vitae purus. Vestibulum in magna rutrum eros bibendum sollicitudin. Duis a mi pellentesque odio dictum rutrum. Fusce aliquet ante eu metus vehicula, non condimentum ex malesuada. Pellentesque in condimentum enim. 
        <img className="wd-float-right"
        src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed commodo, enim suscipit efficitur iaculis, tortor metus bibendum est, non consequat sapien lorem aliquam orci. Quisque at lectus sit amet neque tempor elementum. In faucibus lectus posuere feugiat tempus. Donec sodales velit nec quam scelerisque, non feugiat purus sagittis. Integer nec odio libero. Ut mattis a mi sit amet vulputate. Sed eget posuere quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam pulvinar velit a ipsum elementum vehicula. Pellentesque aliquam, nibh tincidunt egestas gravida, lectus libero molestie justo, quis vestibulum est velit et elit. Quisque accumsan ultricies est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut efficitur, sem ut ornare venenatis, sem enim blandit lacus, vel euismod risus purus non mi. Pellentesque a hendrerit metus. 
        Aenean vitae purus quis neque sollicitudin placerat scelerisque sit amet dui. Donec posuere faucibus diam, sit amet viverra dolor euismod eu. Fusce placerat odio vel urna finibus, sed volutpat sem pretium. Pellentesque efficitur fringilla augue, id interdum mauris feugiat eget. Nunc laoreet felis ac ullamcorper porttitor. Nulla dapibus quis libero vitae feugiat. Integer lobortis cursus ante. Pellentesque sed lectus ligula. In pharetra lectus quis molestie sollicitudin. Vivamus id fringilla sapien. Sed pulvinar, est eu auctor pellentesque, metus ligula molestie sapien, eu bibendum eros nisi vitae odio. In tincidunt gravida dignissim. Quisque fringilla nisi vitae ultricies tempor. Cras maximus semper convallis. 
        Fusce rutrum mauris eget facilisis congue. Suspendisse porttitor mattis velit maximus varius. Duis blandit vehicula arcu, ac tempus mauris lacinia quis. Etiam rhoncus mauris in arcu convallis, sed auctor ante iaculis. In dignissim a massa ut condimentum. Integer pellentesque condimentum lectus, et laoreet nisl mollis a. Curabitur luctus a quam a elementum. Fusce ornare elementum mi ullamcorper hendrerit. Aliquam erat volutpat. Sed finibus felis id sapien pharetra mattis. Aliquam nunc felis, egestas ut lectus imperdiet, tincidunt mattis felis. Mauris scelerisque mi aliquam convallis tincidunt. Maecenas eu malesuada odio. 
        <img className="wd-float-left"
        src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
        Curabitur pharetra tempor urna. Aliquam id gravida risus. Aenean non tortor pharetra, venenatis tortor iaculis, cursus nulla. Proin iaculis tortor dignissim risus dictum mollis. Duis varius ex sit amet enim pellentesque fermentum quis vitae justo. Suspendisse vulputate, diam ut aliquet tristique, dui orci porttitor leo, a imperdiet erat lacus quis nisl. Etiam risus turpis, fringilla et erat vitae, consequat sollicitudin sapien. Aenean porttitor diam turpis, non tristique mauris convallis non. 
        Cras nulla turpis, rhoncus eu tellus in, fringilla congue ipsum. In hac habitasse platea dictumst. Etiam sed feugiat urna. Integer vitae lacus sed ipsum rutrum rhoncus sed sit amet libero. Pellentesque ultrices felis id dui egestas, quis ultricies felis ultrices. Nullam condimentum nulla vitae tempor posuere. Duis non felis ligula. Suspendisse nisl arcu, auctor finibus justo sit amet, tempor pretium eros. 
        Maecenas eget nunc dolor. Duis gravida pulvinar arcu. Vestibulum scelerisque posuere nulla, bibendum rutrum quam porttitor a. Maecenas suscipit sapien sed risus pellentesque, sed elementum leo venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend nec sapien vel pretium. Fusce lectus erat, tristique a eros vel, faucibus molestie sem. Aenean tempus malesuada iaculis. Quisque non facilisis eros. Integer quis metus odio. Sed accumsan tellus nec lobortis malesuada. Donec at mi gravida, tristique quam vel, mattis quam. Etiam arcu lectus, suscipit a lorem id, vestibulum aliquam nulla. Morbi sodales sed purus sed dictum. Pellentesque viverra dignissim lectus, non efficitur dui varius in. Curabitur malesuada sem lectus, sit amet interdum lorem bibendum sit amet. 
        <div className="wd-float-done"></div>
      </div>
      
      <div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-yellow">
          Yellow </div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-blue wd-fg-color-white">
          Blue </div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-red">
          Red </div>
        <img className="wd-float-right"
          src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
        <div className="wd-float-done"></div>
      </div>
    </div>
  );
}